### ISSUE TITLE
Cannot attach Kotlin scripts

### ISSUE THREAD

**Issue by SWRHARD** [utopia-rise/godot-kotlin-jvm#470] opened 2023-06-27 07:03 UTC
When i'm trying to attach kotlin script (Simple.kt) to a node, i got errors and the field "Language" are not changed to Kotlin
![image](https://github.com/utopia-rise/godot-kotlin-jvm/assets/24650584/aea934bb-adf9-4f8d-b4e1-16d3704aa367)

**Godot version**: 4.0.3 stable

**Comment by piiertho** [comment] 2023-06-27 07:33
Hello !
In 4.0 you need to attach the `.gdj` file that is generated at compile time.
See #441

**Comment by SWRHARD** [comment] 2023-06-27 07:53
> 

Hello! Okay, i read this topic, but still dont understand how to generate .gdj files from idea, i have Simple.kt file:

`    @RegisterClass
     class Simple: Spatial() {
    @RegisterFunction
    override fun _ready() {
        GD.print("Hello world!")
    }
}`

i build the project (./gradlew build)  and gdj file has to appear? Thanks

**Comment by piiertho** [comment] 2023-06-27 07:54
Can you provide your gradle build script ?

**Comment by SWRHARD** [comment] 2023-06-27 07:57
build.gradle.kts

      plugins {
          kotlin("jvm") version "1.7.20"
          id("com.utopia-rise.godot-kotlin-jvm") version "0.6.0-3.5.2"
      }
      
      group = "org.example"
      version = "1.0-SNAPSHOT"
      
      repositories {
          mavenCentral()
      }
      
      dependencies {
          testImplementation(kotlin("test"))
      }
      
      tasks.test {
          useJUnitPlatform()
      }
      
      tasks.withType<KotlinCompile> {
          kotlinOptions.jvmTarget = "1.8"
      }

**Comment by piiertho** [comment] 2023-06-27 08:00
You're using godot kotlin `0.6.0-3.5.2`, which is built for godot `3.5.2`.
As we did not finished 4.0 work yet, you will need to build locally this repo (master branch) or use dependency substitution to test godot with 4.0

**Comment by SWRHARD** [comment] 2023-06-27 09:12
okay, thanks! probably i will use godot 3.5.2 now

**Comment by piiertho** [comment] 2023-06-27 09:31
You need godot with kotlin module: https://github.com/utopia-rise/godot-kotlin-jvm/releases

**Comment by SWRHARD** [comment] 2023-06-27 11:08
> You need godot with kotlin module: https://github.com/utopia-rise/godot-kotlin-jvm/releases

Yee now it works! But my script now working, i attached it to sprite node:
       
    @RegisterClass
    class Simple: Sprite() {        
	          @RegisterFunction
	          override fun _ready() {
		          GD.print("I am ready!")
	          }
          }
But the scene is closed immediately, i have two rows in console:

    --- Debugging process started ---
    --- Debugging process stopped ---

If i remove my script, scene works)

**Comment by chippmann** [comment] 2023-08-13 12:23
0.5.2 was a broken build 0.6.2 should work without issues.

**Comment by CedNaru** [comment] 2023-10-04 00:06
Closing issue as there is no news and the logs provided didn't contain any debug symbols that could help. 
The user is free to open another issue if the problem is still ongoing.

**Closed by CedNaru** 2023-10-04 00:06 UTC
