### ISSUE TITLE
How to free a PackedScene instance?

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#185] opened 2021-04-24 16:24 UTC
Let's say I've manually loaded a scene. How can I free it?

```kotlin
object RootSceneManager : GodotStatic {
    val loginScene = ResourceLoader.load("res://src/main/kotlin/clientjvm/scenes/login/LoginScene.tscn") as PackedScene

    init {
        registerAsSingleton()
    }

    override fun collect() {
        loginScene.free()
    }
}
```

The problem is that when I do `loginScene.free()`, then I get this error:
```log
ERROR: MethodBind0<class Node>::call: Condition "!instance" is true. Returned: Variant()
   At: D:\a\godot-kotlin-jvm\godot-kotlin-jvm\core\method_bind.gen.inc:132
ERROR: Godot-JVM: Can't 'free' a reference.
   At: modules\kotlin_jvm\src\transfer_context.cpp:206
```

On the other hand if I don't free it, then I get this error:
```log
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void godot.core.GarbageCollector$MemoryBridge.notifyLeak()'
	at godot.core.GarbageCollector$MemoryBridge.notifyLeak(Native Method)
	at godot.core.GarbageCollector.cleanUp(GarbageCollector.kt:296)
Godot-JVM: WARNING: Some JVM godot instances are leaked.
Leaked references:
    [PackedScene:1189]
```

**Comment by Humberd** [comment] 2021-04-24 16:29
How do you catch an exception?

```kotlin
try {
    loginScene.free()
    gameScene.free()
} catch (e: Throwable) {

}
```

I can't catch this error.

**Comment by piiertho** [comment] 2021-04-24 16:31
This exception is at closing of module. PackedScene inherits Reference, it should be free automatically. Maybe a problem with singleton cleaning ?
Can you try in a classic object ?

**Comment by CedNaru** [comment] 2021-04-24 16:32
Just like in the regular Godot, you can't use free on a Reference.
If you try to free a PackedScene in GDScript you are going to get the same error.
I think you can't catch it because the error is on the C++ side.

In the case of a reference, you just need to no longer have a variable pointing to it.
Just make your variable a var and set it to null in collect.
The same way I did in the example in the doc:
https://godot-kotl.in/en/latest/advanced/kotlin-singleton/

**Comment by piiertho** [comment] 2021-04-24 16:32
Ah, forgot about singleton, assign it to null when cleaning

**Comment by Humberd** [comment] 2021-04-24 16:39
@CedNaru I still get the error

```kotlin

var loginScene = ResourceLoader.load("res://src/main/kotlin/clientjvm/scenes/login/LoginScene.tscn") as PackedScene?

override fun collect() {
    loginScene = null
}
```

```
ERROR: MethodBind0<class Node>::call: Condition "!instance" is true. Returned: Variant()
   At: D:\a\godot-kotlin-jvm\godot-kotlin-jvm\core\method_bind.gen.inc:132
Godot-JVM: Shutting down JVM ...
```

**Comment by CedNaru** [comment] 2021-04-24 17:34
Ho this is interesting.
Maybe it's because it's actually a Resource loaded from the disk so Godot already clean it because it's stored in a cache
But the JVM instance still exists and when the JVM tried to unref it when it's closing you get that error because it's already dead.
But just speculating, that's only the third issue that I have when dealing with Reference/Resources XD.

**Comment by CedNaru** [comment] 2021-04-24 18:11
Just checked the GDScript for Reference

![image](https://user-images.githubusercontent.com/31470327/115968632-1640da80-a539-11eb-8a94-3a0f44a0850b.png)

And yeah I got an error if I try to delete it directly:

![image](https://user-images.githubusercontent.com/31470327/115968651-2a84d780-a539-11eb-8bce-5b3e4c0b1b25.png)

Leaving that here as a memo. I was sure anymore if it was a behavior we created ourselves or not. But not it's really from Godot.

**Comment by CedNaru** [comment] 2021-04-25 15:20
Regarding the C++ error. It's just an error that Godot prints but it's not an exception and doesn't prevent the rest of the code to be executed.
So there is nothing to catch in the first place.

**Comment by CedNaru** [comment] 2021-04-25 15:38
I can't reproduce the issue
I created this singleton
![image](https://user-images.githubusercontent.com/31470327/115999688-fc60cf80-a5ec-11eb-883d-cf3cd9e900a6.png)

And the JVM shuts down just fine.

![image](https://user-images.githubusercontent.com/31470327/115999703-08e52800-a5ed-11eb-911c-d92f63ec22bf.png)

**Comment by Humberd** [comment] 2021-04-27 21:29
I did this and the problem is gone

```kotlin
private fun clearCurrentScene() {
    if (node != null && GD.isInstanceValid(node)) {
        node.queueFree()
    }
    node = null
}
```

@CedNaru did you create a node out of it? Because I did.

**Closed** 2021-04-30 15:21 UTC
Labels: bug, topic:core
