### ISSUE TITLE
Exported properties doesn't hold its value on the inspector after closing and opening the project

### ISSUE THREAD

**Issue by Serutab** [utopia-rise/godot-kotlin-jvm#652] opened 2024-06-14 19:04 UTC
This is something that I noticed when I set an exported `TextureButton` on my script. At the begining I thought I forgot to save the project before closing. Then I set again the value and this time I made sure I saved the project before closing it. 

Oddly enough this only happens on my project, I tried with the GDQuest's sample project and its not happening. This makes me think I'm doing something wrong which is causing the issue.

Having this said, I made a bit of research trying to find a "pattern" to discover when this happens without success because it always happens. This were the tests:

- Tried with default null value.
```
@Export
@RegisterProperty
var myTextureButton: TextureButton? = null
````

- Tried with lateinit var
```
@Export
@RegisterProperty
lateinit var myTextureButton: TextureButton
````

- Tried with a `Double` var with default value
```
@Export
@RegisterProperty
var myDoubleValue: Double = 2.0
````

- Setting the script on a new scene.
- Setting the script on a node whicih is embedded on another scene.
- Setting the script on a node which is not embedded on another scene.

All of them were exported correctly into de Godot's inspector and I was able to change its value. Everything works fine until I save the scene, close the project then open it again. 

I'm using IntelliJ IDEA 2024.1.3 (Ultimate Edition) with the plugin version 0.9.1-4.2.2 and the latest Godot build v4.2.2.stable.custom_build [15073afe3] (0.9.1-4.2.2) which was released on May 7.

**Comment by CedNaru** [comment] 2024-09-26 03:32
Sorry, I forgot to answer to that issue.
Since the last release, I fixed several bugs related to the inspector. Currently, I'm not able to reproduce the behaviour you described, so I can assume it's fixed.
I'm still keeping that issue open until it's confirmed to not happen again with the incoming release.

**Comment by CedNaru** [comment] 2024-10-12 18:45
We didn't run into that issue again since the latest release, so closing the issue

**Closed by CedNaru** 2024-10-12 18:45 UTC
