### ISSUE TITLE
[Proposal] Print JVM stack trace when the error is being thrown inside a cpp file.

### ISSUE THREAD

**Issue by Humberd** [utopia-rise/godot-kotlin-jvm#186] opened 2021-04-24 16:30 UTC
It would be cool to have it, so that we would know what went wrong

**Comment by piiertho** [comment] 2021-08-25 08:53
Exception should appear in classic console or terminal.
We can't do much about this, the stream to where JVM prints is handled by JVM implementation.
When calling `void ExceptionDescribe()` JVM will output it to `sdterr`. There is no easy way for us to retreive the message.

**Comment by chippmann** [comment] 2021-08-25 08:58
@piiertho I don't think this is what the issue describes. As I understand it; the problem is when a crash happens inside cpp land and not the jvm. Then no java stacktrace is printed. Only a dump from cpp land is printed.
What this issue requests (as far as i understand it) is that when a cpp crash happens, the jvm stacktrace should be printed as well, if a call was coming from jvm land.
This would enable easier debugging.

**Comment by Humberd** [comment] 2021-08-25 09:06
What @chippmann said was exactly my problem. I wrote a bunch of code, executed it and then the cpp part crashed and I didn't know which JVM call caused that, which resulted in putting logs every line.

**Comment by CedNaru** [comment] 2024-05-15 00:45
To close after #627 is merged

**Comment by chippmann** [comment] 2024-05-15 03:58
> @piiertho I don't think this is what the issue describes. As I understand it; the problem is when a crash happens inside cpp land and not the jvm. Then no java stacktrace is printed. Only a dump from cpp land is printed.
> What this issue requests (as far as i understand it) is that when a cpp crash happens, the jvm stacktrace should be printed as well, if a call was coming from jvm land.
> This would enable easier debugging.

@CedNaru i don't think that my PR solves this issue. It still only handles a jvm exception but not a print of the jvm stacktrace if no error has happened in jvm but one in cpp (like cannot find node by path as node is not in scene tree)

**Comment by CedNaru** [comment] 2024-05-15 10:36
I see. Then 4.3 will solve the issue, there is a new API call that makes a language print it's current stacktrace, we will just have to implement it by calling a dummy Jvm method that will only throw an exception.

**Closed** 2024-09-22 13:37 UTC
Labels: topic:core
